version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PGHOST: postgres
      PGUSER: myuser
      PGPASSWORD: mypassword
      PGDATABASE: postgres
      PGPORT: 5432
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
